### ISSUE TITLE
[FEATURE] Ability to set/use warehouses for a notebook task (JobTaskNotebookTask)

### ISSUE THREAD

**Issue by goda** [okube-ai/laktory#265]
### Problem Statement

Right now a notebook task can only be specified to run using a job compute, or serverless. But Databricks allows notebook tasks (that contain only SQL) to be run using SQL warehouses as well. An example of a job task I have in Databricks:

```yaml
  - task_key: conformed_calendar_param
    notebook_task:
      notebook_path: /etl/notebook
      base_parameters:
        schema_source: landing
        primary_key: ID
      source: WORKSPACE
      warehouse_id: xxxxxxxx
    max_retries: 1
    min_retry_interval_millis: 0
```

When I try and use the YAML code above using laktory, it fails due to the `warehouse_id` not being part of `JobTaskNotebookTask`

### Proposed Solution

Add a new property in `JobTaskNotebookTask` that will allow for specifying of `warehouse_id` which will ensure that the notebook task is executed using that specific warehouse.

### Additional Context

We could use a `JobTaskSQLTask` instead, but the notebook tasks are nicer because they are formatted with markdown, and show each query's output in the executed notebook.

According to databricks provider documentation, `warehouse_id` should be specifiable in a notebook_task. See https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#notebook_task
