### ISSUE TITLE
[BUG] Resources with same names in stack.yaml are not being picked up by Terraform

### ISSUE THREAD

**Issue by bijilsubhash** [okube-ai/laktory#294]
### Preliminary checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pypi.org/project/laktory/) of laktory.

### Description

Might be worth updating the doc to state that `name` must be unique to all resources. The below example `stack.yaml` was not detecting all of the resources during deployment/preview due to conflicting `name` for task and volume.

### Example Code

```yaml
resources:
  databricks_jobs:
    client-name-dev:
      clusters:
      - name: main
        node_type_id: Standard_DS3_v2
        num_workers: 1
        spark_version: 15.2.x-scala2.12
      name: client-name
      tasks:
      - job_cluster_key: main
        libraries:
        - whl: /Volumes/utils/default/utils/*****.whl
        notebook_task:
          base_parameters:
            CLIENT_NAME: client-name
            TENANT_ID: *******
          notebook_path: /notebooks/*****.py
        task_key: *****_client-name
  databricks_notebooks:
    servicetitan_ingestion_notebook:
      access_controls: []
      dirpath: /Workspace/Notebooks/
      language: PYTHON
      path: /Workspace/Notebooks/servicetitan_ingestion_notebook.py
      source: ./notebooks/servicetitan_ingestion_notebook.py
  databricks_volumes:
    client-name-dev:
      catalog_name: client-name-catalog
      name: client-name
      schema_name: raw_data
      storage_location: abfss://client-name@******.dfs.core.windows.net/raw_data
      volume_type: EXTERNAL
   ```

### Installed Versions

<details>
Laktory version info:
--------------------
laktory-0.4.14
path-/Users/bijil/Library/Caches/pypoetry/virtualenvs/servicetitan-data-ingestion-JjHUMnjM-py3.11/lib/python3.11/site-packages/laktory
python-3.11.5 (v3.11.5:cce6ba91b3, Aug 24 2023, 10:50:31) [Clang 13.0.0 (clang-1300.0.29.30)]
platform-macOS-13.5-x86_64-i386-64bit
--------------------
azure-identity-1.18.0
azure-storage-blob-12.23.1
black-NOT FOUND
boto3-NOT FOUND
databricks-sdk-NOT FOUND
deltalake-NOT FOUND
flit-NOT FOUND
inflect-7.4.0
mkdocs-NOT FOUND
mkdocs-material-NOT FOUND
mkdocs-video-NOT FOUND
mkdocstrings-NOT FOUND
networkx-3.4.2
numpy-1.26.3
pandas-NOT FOUND
planck-0.0.6
plotly-NOT FOUND
polars-NOT FOUND
prompt_toolkit-3.0.48
pulumi-NOT FOUND
pulumi_databricks-NOT FOUND
pyarrow-17.0.0
pydantic-2.9.2
pyspark-NOT FOUND
pytest-NOT FOUND
pytest-cov-NOT FOUND
pytest-examples-NOT FOUND
python-dateutil-2.9.0.post0
pyyaml-6.0.2
settus-0.0.11
sqlparse-NOT FOUND
typer-0.12.5
typing_extensions-4.12.2
yfinance-NOT FOUND
</details>
