### ISSUE TITLE
[BUG] Variables in stack.yaml not accessible in conditional clauses of child YAML files

### ISSUE THREAD

**Issue by bijilsubhash** [okube-ai/laktory#362]
### Preliminary checks

- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the [latest version](https://pypi.org/project/laktory/) of laktory.

### Description

Variables defined at the root level in `stack.yaml` are not being recognized when used within conditional variable clauses in lower-level YAML files (e.g., in resources/*.yaml files). This limits our ability to create environment-specific configurations using conditionals.

### Expected Behavior
Variables defined in `stack.yaml` should be accessible throughout the entire configuration hierarchy, including within conditional clauses in child YAML files.

### Example Code

Here is the yaml:

```yaml
name: transformation
environments:
  prod:
    variables:
      env: prod
      databricks_host: ${vars.DATABRICKS_HOST_PROD}
      databricks_token: ${vars.DATABRICKS_TOKEN_PROD}
  dev:
    variables:
      env: dev
      catalog: sandbox
      databricks_host: ${vars.DATABRICKS_HOST_DEV}
      databricks_token: ${vars.DATABRICKS_TOKEN_DEV}
resources:
  pipelines:
    client-pipeline: !use resources/pipelines/pipeline.yaml
```

In `resources/pipelines/pipeline.yaml`

```yaml
name: ${vars.client}-servicetitan-pipeline
orchestrator: DATABRICKS_JOB

databricks_job:
  tags:
    client: ${vars.client}
    env: ${vars.env}
  config_file:
    access_controls:
      - group_name: group-admin
        permission_level: CAN_MANAGE

variables:
  client: client_name
  catalog: ${{ vars.catalog if vars.env == 'dev' else vars.client }}
  stg_schema: ${{ vars.client if vars.env == 'dev' else 'stg' }}
  int_schema: ${{ vars.client if vars.env == 'dev' else 'int' }}
  fct_schema: ${{ vars.client if vars.env == 'dev' else 'fct' }}
  rpt_schema: ${{ vars.client if vars.env == 'dev' else 'rpt' }}
  dim_schema: ${{ vars.client if vars.env == 'dev' else 'dim' }}
```

`catalog` is parsed as:

```bash
INFO:laktory.models.datasinks.tabledatasink:Dropping TABLE ${{ vars.catalog if vars.env == 'dev' else vars.client }}.client.dim_table
```

Everything else seems to work including `vars.env` in the tags, which is defined in stack.yaml and also `vars.client` which is defined in this yaml.

### Installed Versions

<details>

laktory = 0.6.3

</details>
